### ISSUE TITLE
How much GPU should it need minimum to run this?

### ISSUE THREAD

**Issue by anonymousz97** [kamalkraj/e5-mistral-7b-instruct#4]
I want to ask about the minimum GPU to run for this model finetuning, hope to receive your response asap. Thanks, again

**Comment by kamalkraj** [comment]
WIth A10, running with a batch size of 1 should be possible with a max seq length of 512. 
You can get the desired batch size by adjusting the gradeint accumulation and multi-gpu

**Comment by anonymousz97** [comment]
Thanks a lots.
